openapi: 3.0.3

info:
  title: Get Users API
  description: API to return people who are listed as either living in a specified city, or whose current coordinates are within 50 miles of that city.
  version: 1.0.0

externalDocs:
  description: GitHub repository
  url: https://github.com/burhan-u/get-users

servers:
- url: http://{server}:{port}
  description: Dev
  variables:
    server:
      default: localhost
    port:
      default: '3000'

paths:
  /users:
    get:
      tags: [users]
      summary: Returns a list of users in London
      description: Returns all users who live in, or whose current coordinates are within 50 miles of London.
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '400':
          description: City location error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example: {message: "Unable to get location of city: London"}
        '500':
          description: External API error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{city}:
    get:
      tags: [users]
      summary: Returns a list of users in city
      description: Returns all users who live in, or whose current coordinates are within 50 miles of specified city.
      parameters:
        - in: path
          name: city
          schema:
            type: string
            example: Paris
          required: true
          description: The city to search users in
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '400':
          description: City location error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example: {message: "Unable to get location of city: Paris"}
        '500':
          description: External API error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /metrics:
    get:
      tags: [metrics]
      summary: Exposes metrics
      description: Returns Prometheus metrics.
      responses:
        '200':
          description: Metrics and values
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Metric'
  /healthcheck:
    get:
      tags: [healthcheck]
      summary: Returns a response if server is running
      description: Returns uptime in seconds.
      responses:
        '200':
          description: A payload containing server uptime
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Uptime'

components:
  schemas:
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: integer
          description: ID
          example: 8
        first_name:
          type: string
          description: First name
          example: Carri
        last_name:
          type: string
          description: Last name
          example: Server
        email:
          type: string
          format: email
          description: Email
          example: cserver7@google.nl
        ip_address:
          type: string
          format: ipv4
          description: IP Address
          example: 222.203.3.67
        latitude:
          type: number
          format: double
          description: Latitude
          example: -6.1130137
        longitude:
          type: number
          format: double
          description: Longitude
          example: 106.1610343
    Uptime:
      type: object
      properties:
        uptime:
          type: number
          format: double
          example: 396.791393124
    Error:
      type: object
      properties:
        message:
          type: string
          example: Error received from API
    Metric:
      type: string
      example: node_process_cpu_user_seconds_total 0.250297
